
version = mod_version
group = mod_group_id

repositories {
    // Player Animator
    maven {
        name = "KosmX"
        url = "https://maven.kosmx.dev/"
        content {
            includeGroup "dev.kosmx.player-anim"
        }
    }

    maven {
        name = "Iron's Maven"
        url = "https://code.redspace.io/releases"
    }

    // Create
    maven {
        name = "Create"
        url = "https://maven.createmod.net"
    }
    maven {
        name = "Registrate"
        url = "https://maven.ithundxr.dev/snapshots"
    }

    // Mekanism
    maven {
        name = "Mekanism"
        url = "https://modmaven.dev"
        content {
            includeGroup "mekanism"
        }
    }
}

base {
    archivesName = "${mod_name}-forge-${minecraft_version}"
}

configurations.configureEach {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}

legacyForge {
    runs {
        client {
            client()
            // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
            var file = file("../runs/client")
            if (!file.exists()) file.mkdirs()
            setGameDirectory file
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
            var file = file("../runs/server")
            if (!file.exists()) file.mkdirs()
            setGameDirectory file
        }

        // applies to all the run configs above
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    implementation project(":ViScriptLib")
    jarJar(project(":ViScriptLib"))

    // Optional
    //铁魔法
//    implementation "io.redspace:irons_spellbooks:${irons_spells_version}"
//    runtimeOnly "io.redspace:irons_lib:${irons_lib_version}"
//    runtimeOnly "dev.kosmx.player-anim:player-animation-lib-forge:${playeranimator_version}"
    //冰火传说
//    implementation "curse.maven:iceandfire-ce-1040076:7722420"
//    runtimeOnly "curse.maven:uranus-1010827:8008516"
//    runtimeOnly "curse.maven:jupiter-1072905:7738312"
    //农夫乐事
    modImplementation "maven.modrinth:farmers-delight:${farmers_delight_version}"
    //机械动力
    modImplementation "maven.modrinth:create:${create_version}"
    modImplementation "net.createmod.ponder:Ponder-Forge-${minecraft_version}:${ponder_version}"
//    runtimeOnly "dev.engine-room.flywheel:flywheel-forge-api-${minecraft_version}:${flywheel_version}"
//    runtimeOnly "dev.engine-room.flywheel:flywheel-forge-${minecraft_version}:${flywheel_version}"
//    runtimeOnly "com.tterrag.registrate:Registrate:${registrate_version}"
    //新生魔艺
//    implementation "curse.maven:ars-nouveau-401955:${ars_nouveau_file}"
    //无尽贪婪：重生
    modCompileOnly "curse.maven:re-avaritia-623969:${re_avaritia_file}"
    //合成拓展
//    implementation "curse.maven:cucumber-272335:${cucumber_file}"
//    implementation "curse.maven:extended-crafting-268387:${extended_crafting_file}"
    //森罗物语：厨房
//    implementation "maven.modrinth:kaleidoscope-cookery:${kaleidoscope_cookery_version}"
    //灾变：L_Ender's Cataclysm
//    implementation "curse.maven:lendercataclysm-551586:${cataclysm_file}"
//    runtimeOnly "curse.maven:lionfish-api-1001614:${lionfish_api_file}"
    //菌类感染：孢子
//    implementation "curse.maven:fungal-infection-spore-678295:${fungal_infection_spore_file}"
    //诡厄巫法：Goety
    modCompileOnly "curse.maven:goety-586095:${goety_file}"
    //东方女仆：Touhou Little Maid
    modImplementation "curse.maven:touhou-little-maid-355044:${touhou_little_maid_file}"
    //通用机械：Mekanism
    modCompileOnly "mekanism:Mekanism:${mekanism_version}"

    //must
//    implementation "maven.modrinth:advanced-loot-info:${advanced_loot_info_version}"
}

// Uncomment the lines below if you wish to configure mixin. The mixin file should be named modid.mixins.json.
mixin {
    add sourceSets.main, "${mod_id}.refmap.json"
    config "${mod_id}.mixins.json"
}

jar {
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json"
    ])
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version        : minecraft_version,
            minecraft_version_range  : minecraft_version_range,
            forge_version            : forge_version,
            forge_version_range      : forge_version_range,
            loader_version_range     : loader_version_range,
            mod_id                   : mod_id,
            mod_name                 : mod_name,
            mod_license              : mod_license,
            mod_version              : mod_version,
            mod_authors              : mod_authors,
            mod_description          : mod_description,
            ldlib2_version           : ldlib2_version,
            viscriptlib_version      : project(":ViScriptLib").mod_version
    ]
    inputs.properties replaceProperties
    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties
    }
}
