org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.228
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
mod_id=viscript_recipe
mod_name=ViScriptRecipe
mod_license=GNU LGPL 3.0
mod_version=1.0.8 beta
mod_group_id=com.zhenshiz
mod_authors=zhenshiz
mod_description=Visual modification of the formula

ldlib2_version=2.2.36
viscriptlib_version= 1.1.6.2

kubejs_version = 2101.7.2-build.368
rhino_version = 2101.2.7-build.81

iris_version=1.8.12+1.21.1-neoforge
sodium_version=mc1.21.1-0.6.13-neoforge
lsp_version=1.13.2
jei_version=5lWKlj9s
advanced_loot_info_version=y8p1Vq83
irons_spells_version=1.21.1-3.15.6
irons_lib_version=1.21.1-1.0.2
playeranimator_version=2.0.4+1.21.1
geckolib_version=4.8.4
curios_version=9.5.1+1.21.1
farmers_delight_version=1.21.1-1.3.2
kaleidoscope_cookery_version=1.3.0-neoforge+mc1.21.1
create_version=6.0.10-280
ponder_version=1.0.82
flywheel_version=1.0.4
registrate_version=MC1.21-1.3.0+67
ars_nouveau_file=8152094
re_avaritia_file=8099035
cucumber_file=8035802
mystical_agriculture_file=8344249
extended_crafting_file=7713533
cataclysm_file=8364209
lionfish_api_file=8345326
fungal_infection_spore_file=8342823
goety_file=8404558
touhou_little_maid_file=8061852
confluence_version=SvvNcTJh
titanium_file=7951516
industrial_foregoing_file=8370717
mekanism_version=1.21.1-10.7.19.85
alloy_smelter_version=1.21.1-1.2.1
